[project]
name = "bjj-rules-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rafael De Moraes Lima", email = "rafaelmrslima@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "ollama>=0.6.2",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.6",
    "python-dotenv>=1.2.3",
]

[project.scripts]
bjj-rules-rag = "bjj_rules_rag:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
